### ISSUE TITLE
connected brick skins dont work

### ISSUE THREAD

**Issue by hamburger-pie** [RedStone576/tetrio-minus#1]
I've tried to add all sorts of skins under connected skins, they dont rlly work-

**Comment by RedStone576** [comment]
any example of one of the skins you tried to use?

**Comment by hamburger-pie** [comment]
> any example of one of the skins you tried to use?

any skin, i realised that the extension defaults to using a skin that i didn't even choose. it overrides any file i put in

**Comment by RedStone576** [comment]
does it look like this
![image](https://user-images.githubusercontent.com/44940224/199755716-44fde4c6-627b-4e11-aca7-84de0ff0951d.png)

**Comment by hamburger-pie** [comment]
> does it look like this ![image](https://user-images.githubusercontent.com/44940224/199755716-44fde4c6-627b-4e11-aca7-84de0ff0951d.png)

yes

**Comment by RedStone576** [comment]
just refresh the extension then
